import 'package:flutter/material.dart';

enum SkillGuideTier {
  normal,
  evolution,
  ultimate,
}

class SkillGuideNode {
  const SkillGuideNode({
    required this.id,
    required this.name,
    required this.description,
    required this.tier,
    required this.requiredLevel,
    required this.unlockCondition,
    required this.parameters,
    required this.color,
    required this.icon,
  });

  final String id;
  final String name;
  final String description;
  final SkillGuideTier tier;
  final String requiredLevel;
  final String unlockCondition;
  final List<String> parameters;
  final Color color;
  final IconData icon;
}

class SkillGuideTree {
  const SkillGuideTree({
    required this.id,
    required this.name,
    required this.role,
    required this.color,
    required this.nodes,
  });

  final String id;
  final String name;
  final String role;
  final Color color;
  final List<SkillGuideNode> nodes;
}

const skillGuideTrees = [
  SkillGuideTree(
    id: 'star_projectile',
    name: '星矢弹幕',
    role: '远程火力 · 自动追踪 · 扇形弹幕',
    color: Color(0xFF8FD7FF),
    nodes: [
      SkillGuideNode(
        id: 'star_projectile_1',
        name: '星矢点火',
        description: '武器会额外发射一枚微型追踪星矢。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: [
          '每次攻击额外 +1 小弹',
          '小弹伤害为主武器 35%',
          '射程为攻击范围的 106%',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.auto_awesome_rounded,
      ),
      SkillGuideNode(
        id: 'star_projectile_2',
        name: '分裂弹道',
        description: '星矢命中后会向附近敌人弹出碎光。',
        tier: SkillGuideTier.normal,
        requiredLevel: '星矢弹幕 Lv 2',
        unlockCondition: '继续选择星矢弹幕',
        parameters: [
          '命中后溅射 1 个附近目标',
          '溅射半径 90',
          '溅射伤害为星矢伤害 55%',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.call_split_rounded,
      ),
      SkillGuideNode(
        id: 'star_projectile_3',
        name: '双星齐射',
        description: '自动射击时左右两侧同时展开副弹道。',
        tier: SkillGuideTier.normal,
        requiredLevel: '星矢弹幕 Lv 3',
        unlockCondition: '继续选择星矢弹幕',
        parameters: [
          '额外弹道增加到 3 枚',
          '副弹道角度约为左右展开',
          '仍使用星矢伤害倍率',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.scatter_plot_rounded,
      ),
      SkillGuideNode(
        id: 'star_projectile_4',
        name: '穿透尾迹',
        description: '星矢穿过第一个目标后继续飞行。',
        tier: SkillGuideTier.normal,
        requiredLevel: '星矢弹幕 Lv 4',
        unlockCondition: '继续选择星矢弹幕',
        parameters: [
          '主弹和星矢穿透 +1',
          '穿透后继续检测下一个敌人',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.trending_flat_rounded,
      ),
      SkillGuideNode(
        id: 'star_projectile_5',
        name: '流星过载',
        description: '星矢进入短暂过载，射速显著提升。',
        tier: SkillGuideTier.normal,
        requiredLevel: '星矢弹幕 Lv 5',
        unlockCondition: '继续选择星矢弹幕',
        parameters: [
          '武器冷却 -18%',
          '星矢数量额外 +1',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.speed_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_star_barrage',
        name: '星河连射',
        description: '武器进入星河连射模式，每 5 次攻击触发扇形弹幕。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '星矢弹幕 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_star_barrage',
        parameters: [
          '每 5 次攻击触发一次',
          '扇形弹幕 9 枚小弹',
          '小弹伤害为主武器 55%',
          '小弹穿透 +1',
        ],
        color: Color(0xFF8FD7FF),
        icon: Icons.blur_on_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'orbit_blade',
    name: '环刃领域',
    role: '近身防线 · 旋转切割 · 风暴扩张',
    color: Color(0xFFC7F7FF),
    nodes: [
      SkillGuideNode(
        id: 'orbit_blade_1',
        name: '第一环刃',
        description: '一枚能量刃围绕你旋转，自动切割贴近敌人。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: [
          '生成 1 个 orbit blade',
          '基础半径 70',
          '每 0.18 秒检测命中',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.trip_origin_rounded,
      ),
      SkillGuideNode(
        id: 'orbit_blade_2',
        name: '双刃回旋',
        description: '第二枚环刃加入轨道，提升近身覆盖率。',
        tier: SkillGuideTier.normal,
        requiredLevel: '环刃领域 Lv 2',
        unlockCondition: '继续选择环刃领域',
        parameters: [
          '环刃数量 +1',
          '两枚环刃对向旋转',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.sync_rounded,
      ),
      SkillGuideNode(
        id: 'orbit_blade_3',
        name: '加速轨道',
        description: '环刃旋转速度提升，更稳定地切开包围。',
        tier: SkillGuideTier.normal,
        requiredLevel: '环刃领域 Lv 3',
        unlockCondition: '继续选择环刃领域',
        parameters: [
          '转速从 2.8 提升到 3.5',
          '命中频率保持 0.18 秒检测',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.rotate_right_rounded,
      ),
      SkillGuideNode(
        id: 'orbit_blade_4',
        name: '裂口切割',
        description: '环刃切割更密集，提供稳定近身伤害。',
        tier: SkillGuideTier.normal,
        requiredLevel: '环刃领域 Lv 4',
        unlockCondition: '继续选择环刃领域',
        parameters: [
          '维持双刃命中覆盖',
          '配合月轮风暴后进入多段切割',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.content_cut_rounded,
      ),
      SkillGuideNode(
        id: 'orbit_blade_5',
        name: '外环扩张',
        description: '环刃轨道变大，覆盖更宽区域。',
        tier: SkillGuideTier.normal,
        requiredLevel: '环刃领域 Lv 5',
        unlockCondition: '继续选择环刃领域',
        parameters: [
          '半径 +22%',
          '基础伤害提升',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.radio_button_unchecked_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_moon_wheel',
        name: '月轮风暴',
        description: '环刃周期性向外扩张成切割风暴，再收回玩家身边。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '环刃领域 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_moon_wheel',
        parameters: [
          '每 8 秒进入一次风暴周期',
          '半径从 70 扩张到约 150',
          '扩张阶段命中半径提升到 34',
        ],
        color: Color(0xFFC7F7FF),
        icon: Icons.cyclone_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'thunder_matrix',
    name: '雷暴矩阵',
    role: '范围清怪 · 周期落雷 · 连锁打击',
    color: Color(0xFFB68CFF),
    nodes: [
      SkillGuideNode(
        id: 'thunder_matrix_1',
        name: '雷标锁定',
        description: '周期性标记一个敌人并落雷。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: [
          '每 3.2 秒落雷',
          '优先选择密集敌群中心',
          '基础伤害为武器伤害 135%',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.flash_on_rounded,
      ),
      SkillGuideNode(
        id: 'thunder_matrix_2',
        name: '二重雷击',
        description: '落雷会额外打击第二个目标。',
        tier: SkillGuideTier.normal,
        requiredLevel: '雷暴矩阵 Lv 2',
        unlockCondition: '继续选择雷暴矩阵',
        parameters: [
          '落雷目标数 +1',
          '依然优先攻击密集区域',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.bolt_rounded,
      ),
      SkillGuideNode(
        id: 'thunder_matrix_3',
        name: '静电残留',
        description: '雷击点留下短暂电场，造成范围伤害。',
        tier: SkillGuideTier.normal,
        requiredLevel: '雷暴矩阵 Lv 3',
        unlockCondition: '继续选择雷暴矩阵',
        parameters: [
          '落点半径 52 范围伤害',
          '范围伤害为落雷伤害 35%',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.blur_circular_rounded,
      ),
      SkillGuideNode(
        id: 'thunder_matrix_4',
        name: '连锁导电',
        description: '雷击会跳向附近敌人。',
        tier: SkillGuideTier.normal,
        requiredLevel: '雷暴矩阵 Lv 4',
        unlockCondition: '继续选择雷暴矩阵',
        parameters: [
          '每次雷击可链 2 次',
          '连锁半径 130',
          '连锁伤害为武器伤害 55%',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.device_hub_rounded,
      ),
      SkillGuideNode(
        id: 'thunder_matrix_5',
        name: '雷云压境',
        description: '雷暴频率提升，优先攻击密集敌群。',
        tier: SkillGuideTier.normal,
        requiredLevel: '雷暴矩阵 Lv 5',
        unlockCondition: '继续选择雷暴矩阵',
        parameters: [
          '冷却 -20%',
          '目标排序优先按附近敌人数量',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.cloudy_snowing,
      ),
      SkillGuideNode(
        id: 'evolve_thunder_chain',
        name: '天罚连锁',
        description: 'Boss 或厚血怪被雷击时，把雷电扩散给周围敌群。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '雷暴矩阵 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_thunder_chain',
        parameters: [
          'Boss/坦克触发大范围连锁',
          '连锁目标上限 12',
          '连锁半径 190',
        ],
        color: Color(0xFFB68CFF),
        icon: Icons.thunderstorm_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'void_magnet',
    name: '虚空磁核',
    role: '拾取成长 · 聚怪牵引 · 黑洞爆发',
    color: Color(0xFF8FE388),
    nodes: [
      SkillGuideNode(
        id: 'void_magnet_1',
        name: '磁核手套',
        description: '经验和金币会更早被吸引。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: [
          '拾取范围 +35%',
          '后续每级继续提升拾取范围',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.control_camera_rounded,
      ),
      SkillGuideNode(
        id: 'void_magnet_2',
        name: '余能回收',
        description: '拾取经验时释放微弱冲击。',
        tier: SkillGuideTier.normal,
        requiredLevel: '虚空磁核 Lv 2',
        unlockCondition: '继续选择虚空磁核',
        parameters: [
          '拾取经验时半径 48 范围伤害',
          '伤害为武器伤害 35%',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.recycling_rounded,
      ),
      SkillGuideNode(
        id: 'void_magnet_3',
        name: '磁场牵引',
        description: '附近小怪会被轻微拉向经验物。',
        tier: SkillGuideTier.normal,
        requiredLevel: '虚空磁核 Lv 3',
        unlockCondition: '继续选择虚空磁核',
        parameters: [
          '普通敌人被经验物轻微牵引',
          '牵引半径 120',
          'Boss 不受牵引影响',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.filter_tilt_shift_rounded,
      ),
      SkillGuideNode(
        id: 'void_magnet_4',
        name: '重力涟漪',
        description: '每次升级会释放一次重力波。',
        tier: SkillGuideTier.normal,
        requiredLevel: '虚空磁核 Lv 4',
        unlockCondition: '继续选择虚空磁核',
        parameters: [
          '升级时半径 120 范围伤害',
          '伤害为武器伤害 75%',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.waves_rounded,
      ),
      SkillGuideNode(
        id: 'void_magnet_5',
        name: '虚空积蓄',
        description: '拾取物越多，下一次爆发越强。',
        tier: SkillGuideTier.normal,
        requiredLevel: '虚空磁核 Lv 5',
        unlockCondition: '继续选择虚空磁核',
        parameters: [
          '继续提升拾取范围',
          '为黑洞核心提供更快触发条件',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.all_inclusive_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_black_hole',
        name: '黑洞核心',
        description: '每收集一定数量经验，生成一个黑洞核心。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '虚空磁核 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_black_hole',
        parameters: [
          '每拾取 18 个经验物触发黑洞',
          '黑洞持续 2 秒',
          '黑洞半径 130',
          '结束时造成范围爆炸',
        ],
        color: Color(0xFF8FE388),
        icon: Icons.lens_blur_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'ice_nova',
    name: '冰霜新星',
    role: '控场保命 · 减速冰环 · 碎冰爆发',
    color: Color(0xFF9BD3FF),
    nodes: [
      SkillGuideNode(
        id: 'ice_nova_1',
        name: '霜环初现',
        description: '周期释放减速冰环，被怪群包围时创造拉开距离的窗口。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: [
          '每 6 秒释放一次冰环',
          '基础半径 90',
          '普通敌人明显减速，Boss 只吃弱减速',
        ],
        color: Color(0xFF9BD3FF),
        icon: Icons.ac_unit_rounded,
      ),
      SkillGuideNode(
        id: 'ice_nova_2',
        name: '寒意延长',
        description: '冰环的减速持续更久。',
        tier: SkillGuideTier.normal,
        requiredLevel: '冰霜新星 Lv 2',
        unlockCondition: '继续选择冰霜新星',
        parameters: ['减速持续 +0.6 秒'],
        color: Color(0xFF9BD3FF),
        icon: Icons.timelapse_rounded,
      ),
      SkillGuideNode(
        id: 'ice_nova_3',
        name: '冰环扩张',
        description: '冰环覆盖更宽的安全区域。',
        tier: SkillGuideTier.normal,
        requiredLevel: '冰霜新星 Lv 3',
        unlockCondition: '继续选择冰霜新星',
        parameters: ['半径 +22%'],
        color: Color(0xFF9BD3FF),
        icon: Icons.radio_button_unchecked_rounded,
      ),
      SkillGuideNode(
        id: 'ice_nova_4',
        name: '碎冰割裂',
        description: '被冰环命中的敌人受到一次低额伤害。',
        tier: SkillGuideTier.normal,
        requiredLevel: '冰霜新星 Lv 4',
        unlockCondition: '继续选择冰霜新星',
        parameters: ['命中造成范围伤害', 'Boss 只受到部分伤害'],
        color: Color(0xFF9BD3FF),
        icon: Icons.grain_rounded,
      ),
      SkillGuideNode(
        id: 'ice_nova_5',
        name: '急冻回路',
        description: '冰霜新星释放频率提升。',
        tier: SkillGuideTier.normal,
        requiredLevel: '冰霜新星 Lv 5',
        unlockCondition: '继续选择冰霜新星',
        parameters: ['冷却 -20%'],
        color: Color(0xFF9BD3FF),
        icon: Icons.speed_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_permafrost_field',
        name: '永冻领域',
        description: '冰环中心短暂冻结普通敌人，结束时释放碎冰伤害。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '冰霜新星 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_permafrost_field',
        parameters: [
          '普通敌人短暂停止移动',
          'Boss 只受到减速',
          '中心区域额外碎冰伤害',
        ],
        color: Color(0xFF9BD3FF),
        icon: Icons.severe_cold_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'fire_trail',
    name: '火焰地毯',
    role: '移动铺场 · 持续燃烧 · 走位输出',
    color: Color(0xFFFF8A3D),
    nodes: [
      SkillGuideNode(
        id: 'fire_trail_1',
        name: '火星足迹',
        description: '移动时每隔一段距离留下一片小火焰。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: ['移动时每 0.8 秒生成火焰区域', '站立时不会无限堆火'],
        color: Color(0xFFFF8A3D),
        icon: Icons.local_fire_department_rounded,
      ),
      SkillGuideNode(
        id: 'fire_trail_2',
        name: '持燃余烬',
        description: '火焰存在时间延长。',
        tier: SkillGuideTier.normal,
        requiredLevel: '火焰地毯 Lv 2',
        unlockCondition: '继续选择火焰地毯',
        parameters: ['火焰持续时间 +35%'],
        color: Color(0xFFFF8A3D),
        icon: Icons.whatshot_rounded,
      ),
      SkillGuideNode(
        id: 'fire_trail_3',
        name: '灼热地表',
        description: '火焰持续伤害提升。',
        tier: SkillGuideTier.normal,
        requiredLevel: '火焰地毯 Lv 3',
        unlockCondition: '继续选择火焰地毯',
        parameters: ['每跳伤害提升'],
        color: Color(0xFFFF8A3D),
        icon: Icons.terrain_rounded,
      ),
      SkillGuideNode(
        id: 'fire_trail_4',
        name: '扩散火舌',
        description: '火焰范围扩大。',
        tier: SkillGuideTier.normal,
        requiredLevel: '火焰地毯 Lv 4',
        unlockCondition: '继续选择火焰地毯',
        parameters: ['半径 +20%'],
        color: Color(0xFFFF8A3D),
        icon: Icons.blur_circular_rounded,
      ),
      SkillGuideNode(
        id: 'fire_trail_5',
        name: '爆燃尾迹',
        description: '火焰首次命中敌人时触发小爆燃。',
        tier: SkillGuideTier.normal,
        requiredLevel: '火焰地毯 Lv 5',
        unlockCondition: '继续选择火焰地毯',
        parameters: ['首次命中触发小范围伤害'],
        color: Color(0xFFFF8A3D),
        icon: Icons.flare_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_inferno_path',
        name: '炼狱轨迹',
        description: '移动轨迹变成更密集、更持久的燃烧带。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '火焰地毯 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_inferno_path',
        parameters: ['火焰生成间隔缩短', '持续时间和范围提升', 'Boss 只吃部分持续伤害'],
        color: Color(0xFFFF8A3D),
        icon: Icons.fireplace_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'poison_spore',
    name: '毒雾孢子',
    role: '持续消耗 · 怪群压制 · 腐蚀扩散',
    color: Color(0xFF70E06B),
    nodes: [
      SkillGuideNode(
        id: 'poison_spore_1',
        name: '孢子落点',
        description: '在最近怪群脚下生成一片毒雾。',
        tier: SkillGuideTier.normal,
        requiredLevel: '战斗升级后可选，技能树 Lv 1',
        unlockCondition: '初始升级池出现',
        parameters: ['每 5 秒生成一个毒雾区域', '优先选择密集怪群'],
        color: Color(0xFF70E06B),
        icon: Icons.bubble_chart_rounded,
      ),
      SkillGuideNode(
        id: 'poison_spore_2',
        name: '毒雾滞留',
        description: '毒雾持续时间增加。',
        tier: SkillGuideTier.normal,
        requiredLevel: '毒雾孢子 Lv 2',
        unlockCondition: '继续选择毒雾孢子',
        parameters: ['持续时间 +30%'],
        color: Color(0xFF70E06B),
        icon: Icons.hourglass_bottom_rounded,
      ),
      SkillGuideNode(
        id: 'poison_spore_3',
        name: '雾团扩散',
        description: '毒雾范围扩大。',
        tier: SkillGuideTier.normal,
        requiredLevel: '毒雾孢子 Lv 3',
        unlockCondition: '继续选择毒雾孢子',
        parameters: ['半径 +20%'],
        color: Color(0xFF70E06B),
        icon: Icons.cloud_rounded,
      ),
      SkillGuideNode(
        id: 'poison_spore_4',
        name: '腐蚀步伐',
        description: '中毒敌人移动速度降低。',
        tier: SkillGuideTier.normal,
        requiredLevel: '毒雾孢子 Lv 4',
        unlockCondition: '继续选择毒雾孢子',
        parameters: ['中毒期间减速 15%'],
        color: Color(0xFF70E06B),
        icon: Icons.directions_walk_rounded,
      ),
      SkillGuideNode(
        id: 'poison_spore_5',
        name: '剧毒脉冲',
        description: '毒雾伤害频率提高。',
        tier: SkillGuideTier.normal,
        requiredLevel: '毒雾孢子 Lv 5',
        unlockCondition: '继续选择毒雾孢子',
        parameters: ['伤害间隔缩短'],
        color: Color(0xFF70E06B),
        icon: Icons.speed_rounded,
      ),
      SkillGuideNode(
        id: 'evolve_corrosive_plague',
        name: '腐蚀瘟疫',
        description: '中毒敌人死亡时爆开小毒雾，把腐蚀扩散给附近敌人。',
        tier: SkillGuideTier.evolution,
        requiredLevel: '毒雾孢子 Lv 5 后，下次升级可选',
        unlockCondition: '选择后标记核心进化：evolve_corrosive_plague',
        parameters: ['中毒小怪死亡后生成小毒雾', 'Boss 不触发扩散', '毒雾数量有全局上限'],
        color: Color(0xFF70E06B),
        icon: Icons.coronavirus_rounded,
      ),
    ],
  ),
  SkillGuideTree(
    id: 'ultimate',
    name: '终极大招',
    role: '双核心进化组合 · 每局最多一个',
    color: Color(0xFFFFD36E),
    nodes: [
      SkillGuideNode(
        id: 'ultimate_star_judgement',
        name: '星陨审判',
        description: '流星与雷暴同时降临，轰击全屏敌群。',
        tier: SkillGuideTier.ultimate,
        requiredLevel: '拥有 2 个指定核心进化后，下次升级可选',
        unlockCondition: '星河连射 + 天罚连锁',
        parameters: [
          '每 0.35 秒召唤一波打击',
          '持续 5 秒',
          '冷却 22 秒',
          'Boss 只受到部分效果',
        ],
        color: Color(0xFFFFD36E),
        icon: Icons.flare_rounded,
      ),
      SkillGuideNode(
        id: 'ultimate_black_moon',
        name: '黑月坍缩',
        description: '黑洞拉起月轮风暴，把敌群撕裂后引爆。',
        tier: SkillGuideTier.ultimate,
        requiredLevel: '拥有 2 个指定核心进化后，下次升级可选',
        unlockCondition: '月轮风暴 + 黑洞核心',
        parameters: [
          '生成玩家周围大黑洞',
          '半径 190',
          '持续 3 秒',
          '冷却 24 秒',
          '结束时造成高额范围爆炸',
        ],
        color: Color(0xFFFFD36E),
        icon: Icons.brightness_2_rounded,
      ),
      SkillGuideNode(
        id: 'ultimate_frost_inferno',
        name: '冰火炼狱',
        description: '冰区与火区交替出现，敌人先减速后被爆燃区域持续灼烧。',
        tier: SkillGuideTier.ultimate,
        requiredLevel: '拥有 2 个指定核心进化后，下次升级可选',
        unlockCondition: '永冻领域 + 炼狱轨迹',
        parameters: [
          '周期生成冰火区域',
          '冰区减速并造成碎冰伤害',
          '火区持续灼烧怪群',
          '冷却 18 秒',
        ],
        color: Color(0xFFFFD36E),
        icon: Icons.local_fire_department_rounded,
      ),
    ],
  ),
];
