import 'weapon_definition.dart';

const _weaponAssetRoot = 'assets/game/grass_game/images/weapons';
const _audioRoot = 'assets/game/grass_game/audio';

const List<WeaponDefinition> grassGameWeaponCatalog = [
  WeaponDefinition(
    id: 'wooden_stick',
    name: '训练木棍',
    family: WeaponFamily.melee,
    attackPattern: WeaponAttackPattern.meleeSweep,
    obtainType: WeaponObtainType.free,
    buyCost: 0,
    baseDamage: 10,
    attacksPerSecond: 1.20,
    range: 70,
    areaRadius: 34,
    pierce: 0,
    knockback: 18,
    effectId: 'knockback',
    upgradeCurve: WeaponUpgradeCurve.melee,
    recommendedCharacterIds: ['runner', 'aotuman', 'jingangman'],
    description: '免费起手武器，朝最近敌人方向扫击，稳定但后期上限普通。',
    baseColorValue: 0xFFD9A441,
    iconAssetPath: '$_weaponAssetRoot/weapon_wooden_stick_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_wooden_stick.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_wooden_stick.webp',
    fireSoundAssetPath: '$_audioRoot/fire_other.wav',
  ),
  WeaponDefinition(
    id: 'bounce_ball',
    name: '弹力球',
    family: WeaponFamily.projectile,
    attackPattern: WeaponAttackPattern.bouncingProjectile,
    obtainType: WeaponObtainType.shop,
    buyCost: 180,
    baseDamage: 7,
    attacksPerSecond: 1.10,
    range: 260,
    areaRadius: 0,
    pierce: 0,
    knockback: 8,
    effectId: 'bounce',
    upgradeCurve: WeaponUpgradeCurve.projectile,
    recommendedCharacterIds: ['guard', 'aomeijia'],
    description: '高速弹跳，适合风筝和处理侧翼敌人。',
    baseColorValue: 0xFFFFC857,
    iconAssetPath: '$_weaponAssetRoot/weapon_bounce_ball_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_bounce_ball.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_bounce_ball.webp',
    fireSoundAssetPath: '$_audioRoot/fire_other.wav',
  ),
  WeaponDefinition(
    id: 'star_dart',
    name: '飞星镖',
    family: WeaponFamily.projectile,
    attackPattern: WeaponAttackPattern.projectile,
    obtainType: WeaponObtainType.shop,
    buyCost: 260,
    baseDamage: 8,
    attacksPerSecond: 1.45,
    range: 300,
    areaRadius: 0,
    pierce: 1,
    knockback: 4,
    effectId: 'pierce',
    upgradeCurve: WeaponUpgradeCurve.projectile,
    recommendedCharacterIds: ['runner', 'beliya'],
    description: '高频穿透投射物，清理直线怪群更稳定。',
    baseColorValue: 0xFF8FD7FF,
    iconAssetPath: '$_weaponAssetRoot/weapon_star_dart_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_star_dart.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_star_dart.webp',
    fireSoundAssetPath: '$_audioRoot/fire_rifle.wav',
  ),
  WeaponDefinition(
    id: 'magnet_bow',
    name: '磁能短弓',
    family: WeaponFamily.projectile,
    attackPattern: WeaponAttackPattern.projectile,
    obtainType: WeaponObtainType.shop,
    buyCost: 360,
    baseDamage: 13,
    attacksPerSecond: 0.85,
    range: 380,
    areaRadius: 0,
    pierce: 0,
    knockback: 6,
    effectId: 'homing',
    upgradeCurve: WeaponUpgradeCurve.projectile,
    recommendedCharacterIds: ['runner', 'sevengar'],
    description: '远程稳定输出，低速角色更安全。',
    baseColorValue: 0xFF90DBF4,
    iconAssetPath: '$_weaponAssetRoot/weapon_magnet_bow_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_magnet_bow.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_magnet_bow.webp',
    fireSoundAssetPath: '$_audioRoot/fire_bolt_action_rifle.wav',
  ),
  WeaponDefinition(
    id: 'return_sickle',
    name: '回旋镰',
    family: WeaponFamily.melee,
    attackPattern: WeaponAttackPattern.boomerang,
    obtainType: WeaponObtainType.shop,
    buyCost: 520,
    baseDamage: 9,
    attacksPerSecond: 1.00,
    range: 95,
    areaRadius: 46,
    pierce: 1,
    knockback: 10,
    effectId: 'return_damage',
    upgradeCurve: WeaponUpgradeCurve.melee,
    recommendedCharacterIds: ['aomeijia', 'beliya'],
    description: '飞出和返回两段伤害，高速角色能主动贴边切怪。',
    baseColorValue: 0xFF8FE388,
    iconAssetPath: '$_weaponAssetRoot/weapon_return_sickle_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_return_sickle.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_return_sickle.webp',
    fireSoundAssetPath: '$_audioRoot/fire_carbine.wav',
  ),
  WeaponDefinition(
    id: 'spark_pistol',
    name: '火花手枪',
    family: WeaponFamily.firearm,
    attackPattern: WeaponAttackPattern.projectile,
    obtainType: WeaponObtainType.shop,
    buyCost: 620,
    baseDamage: 5,
    attacksPerSecond: 3.60,
    range: 330,
    areaRadius: 0,
    pierce: 0,
    knockback: 2,
    effectId: 'spark_crit',
    upgradeCurve: WeaponUpgradeCurve.firearm,
    recommendedCharacterIds: ['guard', 'runner'],
    description: '高射速低伤害，适合低攻角色靠频率补输出。',
    baseColorValue: 0xFFFF8A4C,
    iconAssetPath: '$_weaponAssetRoot/weapon_spark_pistol_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_spark_pistol.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_spark_pistol.webp',
    fireSoundAssetPath: '$_audioRoot/fire_signal_pistol.wav',
  ),
  WeaponDefinition(
    id: 'frost_staff',
    name: '冰霜法杖',
    family: WeaponFamily.control,
    attackPattern: WeaponAttackPattern.projectile,
    obtainType: WeaponObtainType.shop,
    buyCost: 760,
    baseDamage: 8,
    attacksPerSecond: 0.95,
    range: 320,
    areaRadius: 34,
    pierce: 0,
    knockback: 4,
    effectId: 'slow_25',
    upgradeCurve: WeaponUpgradeCurve.control,
    recommendedCharacterIds: ['aomeijia', 'sevengar'],
    description: '减速控场，给慢速角色争取走位空间。',
    baseColorValue: 0xFF9BD3FF,
    iconAssetPath: '$_weaponAssetRoot/weapon_frost_staff_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_frost_staff.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_frost_staff.webp',
    fireSoundAssetPath: '$_audioRoot/fire_marksman_rifle.wav',
  ),
  WeaponDefinition(
    id: 'scatter_blunder',
    name: '霰弹铳',
    family: WeaponFamily.firearm,
    attackPattern: WeaponAttackPattern.coneShot,
    obtainType: WeaponObtainType.shop,
    buyCost: 900,
    baseDamage: 6,
    attacksPerSecond: 0.70,
    range: 230,
    areaRadius: 0,
    pierce: 0,
    knockback: 10,
    effectId: 'spread_5',
    upgradeCurve: WeaponUpgradeCurve.firearm,
    recommendedCharacterIds: ['jingangman', 'aotuman'],
    description: '近距离扇形散射，适合高血角色顶住怪潮。',
    baseColorValue: 0xFFFFD166,
    iconAssetPath: '$_weaponAssetRoot/weapon_scatter_blunder_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_scatter_blunder.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_scatter_blunder.webp',
    fireSoundAssetPath: '$_audioRoot/fire_shotgun.wav',
  ),
  WeaponDefinition(
    id: 'thunder_needle',
    name: '雷针发射器',
    family: WeaponFamily.energy,
    attackPattern: WeaponAttackPattern.chainLightning,
    obtainType: WeaponObtainType.shop,
    buyCost: 1080,
    baseDamage: 11,
    attacksPerSecond: 0.80,
    range: 360,
    areaRadius: 56,
    pierce: 0,
    knockback: 4,
    effectId: 'chain_1',
    upgradeCurve: WeaponUpgradeCurve.energy,
    recommendedCharacterIds: ['beliya', 'aotuman'],
    description: '命中后链到附近目标，适合处理密集怪群。',
    baseColorValue: 0xFFB68CFF,
    iconAssetPath: '$_weaponAssetRoot/weapon_thunder_needle_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_thunder_needle.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_thunder_needle.webp',
    fireSoundAssetPath: '$_audioRoot/fire_semi_auto_rifle.wav',
  ),
  WeaponDefinition(
    id: 'flame_sprayer',
    name: '火焰喷壶',
    family: WeaponFamily.energy,
    attackPattern: WeaponAttackPattern.flameStream,
    obtainType: WeaponObtainType.shop,
    buyCost: 1180,
    baseDamage: 4,
    attacksPerSecond: 5.00,
    range: 160,
    areaRadius: 28,
    pierce: 0,
    knockback: 1,
    effectId: 'burn_ground',
    upgradeCurve: WeaponUpgradeCurve.energy,
    recommendedCharacterIds: ['aotuman', 'aomeijia'],
    description: '近距离持续火舌，适合高机动角色绕圈铺场。',
    baseColorValue: 0xFFFF6B35,
    iconAssetPath: '$_weaponAssetRoot/weapon_flame_sprayer_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_flame_sprayer.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_flame_sprayer.webp',
    fireSoundAssetPath: '$_audioRoot/fire_flamethrower.wav',
  ),
  WeaponDefinition(
    id: 'mini_grenade',
    name: '小型榴弹炮',
    family: WeaponFamily.explosive,
    attackPattern: WeaponAttackPattern.lobbedExplosion,
    obtainType: WeaponObtainType.shop,
    buyCost: 1450,
    baseDamage: 26,
    attacksPerSecond: 0.38,
    range: 420,
    areaRadius: 80,
    pierce: 0,
    knockback: 16,
    effectId: 'explosion',
    upgradeCurve: WeaponUpgradeCurve.explosive,
    recommendedCharacterIds: ['sevengar', 'jingangman'],
    description: '慢速大范围爆破，清厚血怪和 Boss 更有优势。',
    baseColorValue: 0xFFFF8A4C,
    iconAssetPath: '$_weaponAssetRoot/weapon_mini_grenade_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_mini_grenade.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_mini_grenade.webp',
    fireSoundAssetPath: '$_audioRoot/fire_grenade_launcher.wav',
  ),
  WeaponDefinition(
    id: 'ball_hammer',
    name: '球锤',
    family: WeaponFamily.melee,
    attackPattern: WeaponAttackPattern.meleeSweep,
    obtainType: WeaponObtainType.craft,
    buyCost: 220,
    baseDamage: 18,
    attacksPerSecond: 0.90,
    range: 95,
    areaRadius: 54,
    pierce: 0,
    knockback: 28,
    effectId: 'heavy_knockback',
    upgradeCurve: WeaponUpgradeCurve.melee,
    recipe: WeaponRecipe(
      materialWeaponIds: ['wooden_stick', 'bounce_ball'],
      craftCost: 220,
    ),
    recommendedCharacterIds: ['aotuman', 'jingangman'],
    description: '重击击退更强，是高血近战角色的第一条合成路线。',
    baseColorValue: 0xFFD9A441,
    iconAssetPath: '$_weaponAssetRoot/weapon_ball_hammer_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_ball_hammer.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_ball_hammer.webp',
    fireSoundAssetPath: '$_audioRoot/fire_other.wav',
  ),
  WeaponDefinition(
    id: 'moon_sickle',
    name: '月牙回旋镰',
    family: WeaponFamily.melee,
    attackPattern: WeaponAttackPattern.boomerang,
    obtainType: WeaponObtainType.craft,
    buyCost: 520,
    baseDamage: 15,
    attacksPerSecond: 1.05,
    range: 125,
    areaRadius: 58,
    pierce: 2,
    knockback: 14,
    effectId: 'outer_ring_bonus',
    upgradeCurve: WeaponUpgradeCurve.melee,
    recipe: WeaponRecipe(
      materialWeaponIds: ['wooden_stick', 'return_sickle'],
      craftCost: 520,
    ),
    recommendedCharacterIds: ['aomeijia', 'beliya'],
    description: '回旋两段伤害，外圈伤害更高。',
    baseColorValue: 0xFF8FE388,
    iconAssetPath: '$_weaponAssetRoot/weapon_moon_sickle_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_moon_sickle.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_moon_sickle.webp',
    fireSoundAssetPath: '$_audioRoot/fire_carbine.wav',
  ),
  WeaponDefinition(
    id: 'storm_ball',
    name: '雷暴弹球',
    family: WeaponFamily.energy,
    attackPattern: WeaponAttackPattern.bouncingProjectile,
    obtainType: WeaponObtainType.craft,
    buyCost: 760,
    baseDamage: 12,
    attacksPerSecond: 1.05,
    range: 340,
    areaRadius: 60,
    pierce: 1,
    knockback: 8,
    effectId: 'bounce_chain',
    upgradeCurve: WeaponUpgradeCurve.energy,
    recipe: WeaponRecipe(
      materialWeaponIds: ['bounce_ball', 'thunder_needle'],
      craftCost: 760,
    ),
    recommendedCharacterIds: ['guard', 'beliya'],
    description: '弹跳时释放小电弧，风筝和清群兼顾。',
    baseColorValue: 0xFFB68CFF,
    iconAssetPath: '$_weaponAssetRoot/weapon_storm_ball_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_storm_ball.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_storm_ball.webp',
    fireSoundAssetPath: '$_audioRoot/fire_semi_auto_rifle.wav',
  ),
  WeaponDefinition(
    id: 'flame_scatter',
    name: '焚风散射器',
    family: WeaponFamily.firearm,
    attackPattern: WeaponAttackPattern.coneShot,
    obtainType: WeaponObtainType.craft,
    buyCost: 920,
    baseDamage: 5,
    attacksPerSecond: 0.75,
    range: 250,
    areaRadius: 36,
    pierce: 0,
    knockback: 8,
    effectId: 'burn_spread',
    upgradeCurve: WeaponUpgradeCurve.firearm,
    recipe: WeaponRecipe(
      materialWeaponIds: ['scatter_blunder', 'flame_sprayer'],
      craftCost: 920,
    ),
    recommendedCharacterIds: ['jingangman', 'aotuman'],
    description: '扇形燃烧弹，近距离怪潮压制更强。',
    baseColorValue: 0xFFFF6B35,
    iconAssetPath: '$_weaponAssetRoot/weapon_flame_scatter_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_flame_scatter.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_flame_scatter.webp',
    fireSoundAssetPath: '$_audioRoot/fire_shotgun.wav',
  ),
  WeaponDefinition(
    id: 'ice_moon',
    name: '冰月轮',
    family: WeaponFamily.control,
    attackPattern: WeaponAttackPattern.orbitSlash,
    obtainType: WeaponObtainType.craft,
    buyCost: 1050,
    baseDamage: 14,
    attacksPerSecond: 0.85,
    range: 145,
    areaRadius: 72,
    pierce: 2,
    knockback: 10,
    effectId: 'ice_orbit_slow',
    upgradeCurve: WeaponUpgradeCurve.control,
    recipe: WeaponRecipe(
      materialWeaponIds: ['frost_staff', 'return_sickle'],
      craftCost: 1050,
    ),
    recommendedCharacterIds: ['aomeijia', 'sevengar'],
    description: '环形冰刃，减速并切割近身敌人。',
    baseColorValue: 0xFF9BD3FF,
    iconAssetPath: '$_weaponAssetRoot/weapon_ice_moon_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_ice_moon.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_ice_moon.webp',
    fireSoundAssetPath: '$_audioRoot/fire_marksman_rifle.wav',
  ),
  WeaponDefinition(
    id: 'storm_hammer',
    name: '天雷链锤',
    family: WeaponFamily.energy,
    attackPattern: WeaponAttackPattern.meleeSweep,
    obtainType: WeaponObtainType.ultimateCraft,
    buyCost: 1800,
    baseDamage: 26,
    attacksPerSecond: 0.72,
    range: 115,
    areaRadius: 88,
    pierce: 0,
    knockback: 34,
    effectId: 'heavy_thunder',
    upgradeCurve: WeaponUpgradeCurve.ultimate,
    recipe: WeaponRecipe(
      materialWeaponIds: ['ball_hammer', 'storm_ball'],
      craftCost: 1800,
    ),
    recommendedCharacterIds: ['beliya', 'jingangman'],
    description: '高攻近战终局武器，每几次重击触发落雷。',
    baseColorValue: 0xFFB68CFF,
    iconAssetPath: '$_weaponAssetRoot/weapon_storm_hammer_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_storm_hammer.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_storm_hammer.webp',
    fireSoundAssetPath: '$_audioRoot/fire_infantry_launcher.wav',
  ),
  WeaponDefinition(
    id: 'star_core_cannon',
    name: '星核榴光炮',
    family: WeaponFamily.explosive,
    attackPattern: WeaponAttackPattern.lobbedExplosion,
    obtainType: WeaponObtainType.ultimateCraft,
    buyCost: 2200,
    baseDamage: 34,
    attacksPerSecond: 0.32,
    range: 460,
    areaRadius: 110,
    pierce: 0,
    knockback: 20,
    effectId: 'gravity_explosion',
    upgradeCurve: WeaponUpgradeCurve.ultimate,
    recipe: WeaponRecipe(
      materialWeaponIds: ['magnet_bow', 'mini_grenade'],
      craftCost: 2200,
    ),
    recommendedCharacterIds: ['sevengar', 'beliya'],
    description: '远程爆破终局武器，爆心带二段吸附。',
    baseColorValue: 0xFFFFD166,
    iconAssetPath: '$_weaponAssetRoot/weapon_star_core_cannon_icon.webp',
    muzzleFlashAssetPath: '$_weaponAssetRoot/muzzle_star_core_cannon.webp',
    projectileAssetPath: '$_weaponAssetRoot/projectile_star_core_cannon.webp',
    fireSoundAssetPath: '$_audioRoot/fire_mortar.wav',
  ),
];
