import 'enemy_config.dart';
import 'game_balance.dart';
import 'skill_config.dart';
import 'wave_config.dart';

class GrassGameConfig {
  const GrassGameConfig({
    required this.version,
    required this.balance,
    required this.enemies,
    required this.skills,
    required this.waves,
  });

  final int version;
  final GameBalance balance;
  final List<EnemyConfig> enemies;
  final List<SkillConfig> skills;
  final List<WaveConfig> waves;

  static const _skillAssetRoot = 'assets/game/grass_game/images/skills';

  static const defaults = GrassGameConfig(
    version: 1,
    balance: GameBalance.defaults,
    enemies: [
      EnemyConfig(
        id: 'basic',
        hp: 12,
        moveSpeed: 132,
        expDrop: 4,
        meleeDamageMin: 5,
        meleeDamageMax: 7,
      ),
      EnemyConfig(
        id: 'lamb',
        hp: 9,
        moveSpeed: 150,
        expDrop: 4,
        meleeDamageMin: 4,
        meleeDamageMax: 6,
      ),
      EnemyConfig(
        id: 'piglet',
        hp: 16,
        moveSpeed: 122,
        expDrop: 5,
        meleeDamageMin: 6,
        meleeDamageMax: 8,
      ),
      EnemyConfig(
        id: 'calf',
        hp: 22,
        moveSpeed: 138,
        expDrop: 6,
        meleeDamageMin: 7,
        meleeDamageMax: 10,
      ),
      EnemyConfig(
        id: 'fast',
        hp: 10,
        moveSpeed: 192,
        expDrop: 6,
        meleeDamageMin: 5,
        meleeDamageMax: 8,
      ),
      EnemyConfig(
        id: 'rooster',
        hp: 14,
        moveSpeed: 178,
        expDrop: 6,
        meleeDamageMin: 6,
        meleeDamageMax: 9,
      ),
      EnemyConfig(
        id: 'turkey',
        hp: 34,
        moveSpeed: 124,
        expDrop: 9,
        meleeDamageMin: 10,
        meleeDamageMax: 14,
      ),
      EnemyConfig(
        id: 'tank',
        hp: 56,
        moveSpeed: 88,
        expDrop: 14,
        meleeDamageMin: 15,
        meleeDamageMax: 22,
      ),
      EnemyConfig(
        id: 'chick',
        hp: 8,
        moveSpeed: 188,
        expDrop: 4,
        meleeDamageMin: 4,
        meleeDamageMax: 6,
      ),
      EnemyConfig(
        id: 'sheep',
        hp: 18,
        moveSpeed: 118,
        expDrop: 6,
        meleeDamageMin: 6,
        meleeDamageMax: 9,
      ),
      EnemyConfig(
        id: 'bull',
        hp: 60,
        moveSpeed: 92,
        expDrop: 15,
        meleeDamageMin: 16,
        meleeDamageMax: 23,
      ),
    ],
    skills: [
      SkillConfig(
        id: 'star_projectile',
        treeId: 'star_projectile',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_star_projectile.webp',
      ),
      SkillConfig(
        id: 'orbit_blade',
        treeId: 'orbit_blade',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_orbit_blade.webp',
      ),
      SkillConfig(
        id: 'thunder_matrix',
        treeId: 'thunder_matrix',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_thunder_matrix.webp',
      ),
      SkillConfig(
        id: 'void_magnet',
        treeId: 'void_magnet',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_void_magnet.webp',
      ),
      SkillConfig(
        id: 'ice_nova',
        treeId: 'ice_nova',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_ice_nova.webp',
      ),
      SkillConfig(
        id: 'fire_trail',
        treeId: 'fire_trail',
        weight: 100,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_fire_trail.webp',
      ),
      SkillConfig(
        id: 'poison_spore',
        treeId: 'poison_spore',
        weight: 90,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_poison_spore.webp',
      ),
      SkillConfig(
        id: 'shadow_guard',
        treeId: 'shadow_guard',
        weight: 95,
        maxLevel: 5,
        iconAssetPath: '$_skillAssetRoot/skill_shadow_guard.png',
      ),
      SkillConfig(
        id: 'evolve_star_barrage',
        treeId: 'star_projectile',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_star_projectile.webp',
        requires: ['star_projectile'],
      ),
      SkillConfig(
        id: 'evolve_moon_wheel',
        treeId: 'orbit_blade',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_orbit_blade.webp',
        requires: ['orbit_blade'],
      ),
      SkillConfig(
        id: 'evolve_thunder_chain',
        treeId: 'thunder_matrix',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_thunder_matrix.webp',
        requires: ['thunder_matrix'],
      ),
      SkillConfig(
        id: 'evolve_black_hole',
        treeId: 'void_magnet',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_void_magnet.webp',
        requires: ['void_magnet'],
      ),
      SkillConfig(
        id: 'evolve_permafrost_field',
        treeId: 'ice_nova',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_ice_nova.webp',
        requires: ['ice_nova'],
      ),
      SkillConfig(
        id: 'evolve_inferno_path',
        treeId: 'fire_trail',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_fire_trail.webp',
        requires: ['fire_trail'],
      ),
      SkillConfig(
        id: 'evolve_corrosive_plague',
        treeId: 'poison_spore',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_poison_spore.webp',
        requires: ['poison_spore'],
      ),
      SkillConfig(
        id: 'evolve_twin_shadow',
        treeId: 'shadow_guard',
        tier: SkillTier.evolution,
        weight: 140,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_shadow_guard.png',
        requires: ['shadow_guard'],
      ),
      SkillConfig(
        id: 'ultimate_star_judgement',
        tier: SkillTier.ultimate,
        weight: 160,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_weapon_fusion_icon.png',
        requires: ['evolve_star_barrage', 'evolve_thunder_chain'],
      ),
      SkillConfig(
        id: 'ultimate_black_moon',
        tier: SkillTier.ultimate,
        weight: 160,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_weapon_fusion_icon.png',
        requires: ['evolve_moon_wheel', 'evolve_black_hole'],
      ),
      SkillConfig(
        id: 'ultimate_frost_inferno',
        tier: SkillTier.ultimate,
        weight: 150,
        maxLevel: 1,
        iconAssetPath: '$_skillAssetRoot/skill_weapon_fusion_icon.png',
        requires: ['evolve_permafrost_field', 'evolve_inferno_path'],
      ),
    ],
    waves: [
      WaveConfig(
        startSecond: 0,
        enemyId: 'basic',
        spawnIntervalSeconds: 0.88,
      ),
      WaveConfig(
        startSecond: 45,
        enemyId: 'fast',
        spawnIntervalSeconds: 0.72,
      ),
      WaveConfig(
        startSecond: 105,
        enemyId: 'tank',
        spawnIntervalSeconds: 1.05,
      ),
    ],
  );
}
